// Generated by CoffeeScript 1.4.0
var Browser, app, chai, global, should;

app = require('../app.js');

Browser = require('zombie');

chai = require('chai');

should = chai.should();

global = {};

app.set('env', 'testing');

app.listen(3000);

describe("Web Client UI", function() {
  var after, browser,
    _this = this;
  browser = new Browser({
    site: 'http://localhost:3000'
  });
  after = function() {
    browser.close();
    return app.close();
  };
  return it("check if browser is defined", function() {
    return browser.should.not.equal(void 0);
  });
});
