// Generated by CoffeeScript 1.4.0
var Browser, app, chai, expect, globals, should;

app = require('../app.js');

Browser = require('zombie');

chai = require('chai');

should = chai.should();

expect = chai.expect;

globals = {};

app.set('env', 'testing');

app.listen(3000);

describe("Web Client UI", function() {
  var after, browser, overlay_cls;
  browser = new Browser({
    site: 'http://localhost:3000'
  });
  overlay_cls = ".drag-active";
  after = function() {
    browser.close();
    return app.close();
  };
  it("check if browser is defined", function() {
    return expect(browser).to.be.ok;
  });
  it("check if overlay is displayed on drag over", function(done) {
    var _this = this;
    browser.visit("/").then(function() {
      return browser.fire("body", 'dragenter').then(function() {
        var overlay;
        overlay = browser.query(overlay_cls);
        expect(overlay).to.exist;
        return done();
      }).fail(function(error) {
        return done(error);
      });
    }).fail(function(error) {
      return done(error);
    });
    return null;
  });
  return it("check if overlay is hidden on drag leave", function(done) {
    var _this = this;
    browser.visit("/").then(function() {
      debugger;      return browser.fire("#drop-mask", 'dragleave').then(function() {
        var overlay;
        overlay = browser.query(overlay_cls);
        expect(overlay).to.not.exist;
        return done();
      }).fail(function(error) {
        return done(error);
      });
    }).fail(function(error) {
      return done(error);
    });
    return null;
  });
});
