// Generated by CoffeeScript 1.4.0
var fs, service;

service = require('../lib/service');

fs = require('fs');

exports.upload = function(req, res) {
  debugger;
  var file, filename, _ref, _results;
  _ref = req.files;
  _results = [];
  for (filename in _ref) {
    file = _ref[filename];
    _results.push(fs.readFile(file.path, {
      encoding: 'utf-8'
    }, function(err, data) {
      file = {
        data: data,
        name: file.name,
        size: file.size,
        type: file.type
      };
      console.log(file);
      return res.send(file);
    }));
  }
  return _results;
};
