// Generated by CoffeeScript 1.4.0
var service;

service = require('../lib/service');

exports.upload = function(req, res) {
  var file, ret_val, s;
  file = {
    name: 'test.txt',
    size: 12,
    type: 'text/plain',
    data: 'Hello World'
  };
  debugger;
  s = new service.PastebinService(file);
  ret_val = s.dispatch();
  return res.send("" + ret_val);
};
