// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.config = {
    pastebin: {
      key: ''
    },
    imgur: {
      key: ''
    }
  };

}).call(this);
