// Generated by CoffeeScript 1.4.0
var root;

root = typeof exports !== "undefined" && exports !== null ? exports : this;

root.pastebin = {
  api_key: '',
  api_url: 'http://pastebin.com/api/api_post.php'
};

root.imgur = {
  api_client_id: '',
  api_client_secret: '',
  api_url: 'https://api.imgur.com/3/image'
};
