// Generated by CoffeeScript 1.4.0
var config, request,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

config = require('./config');

request = require('request');

exports.PastebinService = (function() {

  function PastebinService(file) {
    this.file = file;
    this.dispatch = __bind(this.dispatch, this);

  }

  PastebinService.prototype.dispatch = function() {
    var request_params, send_params;
    send_params = {
      api_dev_key: config.pastebin.api_key,
      api_option: 'paste',
      api_paste_code: this.file.data,
      api_paste_name: this.file.name,
      api_paste_private: 1
    };
    request_params = {
      method: 'POST',
      uri: config.pastebin.url,
      form: send_params
    };
    return request(request_params, function(error, response, body) {
      if (!error && response.statusCode === 200) {
        return body;
      }
    });
  };

  return PastebinService;

})();
