// Generated by CoffeeScript 1.4.0
var PastebinService, Service, config, request,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

config = require('./config');

request = require('request');

Service = (function() {

  function Service() {}

  Service.prototype._handle_body = function(body) {};

  Service.prototype.dispatch = function(file, callback) {};

  return Service;

})();

PastebinService = (function(_super) {

  __extends(PastebinService, _super);

  function PastebinService() {}

  PastebinService.prototype.dispatch = function(file, callback) {
    var request_params, send_params;
    send_params = {
      api_dev_key: config.pastebin.api_key,
      api_option: 'paste',
      api_paste_code: file.data,
      api_paste_name: file.name,
      api_paste_private: 1
    };
    request_params = {
      method: 'POST',
      uri: config.pastebin.url,
      form: send_params
    };
    return request(request_params, function(error, response, body) {
      var message, url, _ref;
      _ref = [null, null], url = _ref[0], message = _ref[1];
      if (error || response.statusCode !== 200) {
        message = body;
      } else {
        url = body;
      }
      return callback(error, file.name, url, message);
    });
  };

  return PastebinService;

})(Service);

exports.PastebinService = PastebinService;
